"""Updating the column parameters if created_by in customers table

Revision ID: c5f9f1f7850f
Revises: cc387a8db21a
Create Date: 2021-07-12 18:28:19.640488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f9f1f7850f'
down_revision = 'cc387a8db21a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
