"""Creating column name in Customers table

Revision ID: cc387a8db21a
Revises: 4d7bf4244225
Create Date: 2021-07-12 18:25:27.040930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc387a8db21a'
down_revision = '4d7bf4244225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'name')
    # ### end Alembic commands ###
